alpha-blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'my_registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles # , only: [:show, :index, :new, :create, :edit, :update] #Creates the route needed
  resources :users, only: %i[index show]
  resources :categories, except: [:destroy]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :users, only: %i[index show]
  get 'upload_pic', to: 'users#upload_pic_get'
  post 'upload_pic_post', to: 'users#upload_pic_post'

  # Defines the root path route ("/")
  # root "posts#index"
end

#  get "/articles", to: "articles#index"  #The route above declares that GET /articles requests are mapped to the index
#   action of ArticlesController.

# resources :articles, only: [:show]

alpha-blog/app/models/article.rb
class Article < ApplicationRecord
  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at description id title updated_at user_id views]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[user categories article_categories]
  end
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 7, maximum: 10_000 }
end

alpha-blog/app/controllers/articles_controller.rb
# frozen_string_literal: false

# Articles controller
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit update]

  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result.includes(:categories).distinct.page(params[:page])

    @pagy, @articles = pagy(@articles, items: 10)
  end

  def show
    @article.increment!(:views)
  end

  def new
    @article = Article.new
  end

  # bypasser la rediction de la police
  def edit
    if authorize @article
      render 'edit'
    else
      flash[:alert] = 'You can only edit your own articles'
      redirect_articles
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_article
    # redirect @article (racourci)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if (authorize @article) && @article.update(article_params)
      flash[:notice] = 'Article was updated successfully'
      redirect_article
    else
      redirect_articles
    end
  end

  def destroy
    if !current_user || (@article.user != current_user && !current_user.admin?)
      flash[:alert] = 'You can only delete your own articles'
      redirect_articles
    else
      @article.destroy
      flash[:notice] = 'Article was successfully deleted'
      redirect_articles
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def redirect_article
    redirect_to article_path(@article)
  end

  def redirect_articles
    redirect_to articles_path
  end
end

alpha-blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

alpha-blog/app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

alpha-blog/app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2> The following errors occured</h2>
<ul> 
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>


    <% end %>
 <% end %>
<%= form_with(model: @article, local: true)  do |f| %>
  <p> 
    <%= f.label :title %><br/> 
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/> 
    <%= f.text_area :description %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

alpha-blog/app/views/articles/edit.html.erb
<h1>Edit article n°<%= @article.id%></h1>
<%= render 'form' %>
<%= link_to 'Index', articles_path %>

alpha-blog/app/views/articles/index.html.erb
<h1>Articles listing page</h1>
<%= search_form_for @q, html: { class: 'd-flex' } do |f| %>

  <%= f.label :title_cont %>
  <%= f.search_field :title_cont %>
  <%= f.submit %>
<% end %>
<%= search_form_for @q, html: { class: 'd-flex' } do |f| %>
  <%= f.label :categories_name_cont, "Category" %>
  <%= f.search_field :categories_name_cont %>
  <%= f.submit "Search" %>
<% end %>


<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :title) %></th>
      <th><%= sort_link(@q, :description) %></th>
      <th><%= sort_link(@q, :views) %></th>
      <th><%= sort_link(@q, :created_at) %></th>
      <th><%= sort_link(@q, :updated_at) %></th>
      <th colspan="3">Actions</th>
      <th>Writer</th>
      <th>Categories</th> 
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title%></td>
      <td><%= article.description%></td>
      <td><%= article.views%></td>
      <td><%= l article.created_at%></td>
      <td><%= article.updated_at.strftime("%d/%m/%Y")%></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <% if policy(article).update? %>
    <td><%= link_to 'Edit', edit_article_path(article) %>
    <% end %>
    <% if policy(article).destroy? %>
    <td><%= link_to 'destroy', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
    <% end %>
<td><%= article.user&.username || "No author" %></td>
    <td><%= article.categories.map(&:name).join(", ") %></td>

    </tr>
    <% end %>
  </tbody>
</table>
<p></p>
<% if user_signed_in? %>
<%= link_to 'Créer un article', new_article_path%>
<% end %>
<%# Note the double equals sign "==" which marks the output as trusted and html safe: %>
<%== pagy_nav(@pagy) %>

alpha-blog/app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>
<%= link_to "Retour à l'index", articles_path %>

alpha-blog/app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title : </strong>
    <%= @article.title %>
</p>
<p><strong>Description : </strong>
    <%= @article.description %>
</p></br>
<p>Written by : <td>
        <%= @article.user.username if @article.user%>
    </td>, id :<%= @article.user.id if @article.user %>
</p></br>
<p>
  <strong>Views:</strong>
  <%= @article.views %>
</p>

<td>
    <%= link_to 'Index' , articles_path %>
</td><% if user_signed_in? && @article.user == current_user %>  |
<td>
    <%= link_to 'Edit' , edit_article_path(@article) %>
</td> |
<%= link_to 'destroy' , article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>