alpha-blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'my_registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles # , only: [:show, :index, :new, :create, :edit, :update] #Creates the route needed
  resources :users, only: %i[index show]
  resources :categories, except: [:destroy]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :users, only: %i[index show]
  get 'upload_pic', to: 'users#upload_pic_get'
  post 'upload_pic_post', to: 'users#upload_pic_post'

  # Defines the root path route ("/")
  # root "posts#index"
end

#  get "/articles", to: "articles#index"  #The route above declares that GET /articles requests are mapped to the index
#   action of ArticlesController.

# resources :articles, only: [:show]

alpha-blog/app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: { case_sensitive: false }, presence: true, length: { minimum: 3, maximum: 15 }
  has_many :article_categories
  has_many :articles, through: :article_categories
  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id id_value name updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[article_categories articles]
  end
end

alpha-blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]

  def new
    @category = Category.new
    response.status = 200
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created'
      redirect_to @category
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category name was successfully updated'
      redirect_to @category
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def index
    @q = Category.ransack(params[:q])
    result = @q.result(distinct: true)
    @pagy, @categories = pagy(result, items: 10)
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    return if user_signed_in? && current_user.admin?

    flash[:alert] = 'Only admins can perform that action'
    redirect_to categories_path
  end
end

alpha-blog/app/views/categories/edit.html.erb
<h1>Showing category</h1>
<p><strong>Name: </strong> <%= @category.name %></p>

<% if user_signed_in? && current_user.admin? %>
  <%= form_with model: @category, local: true do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="actions">
      <%= form.submit "Update Category" %>
    </div>
  <% end %> 
<% end %> 

alpha-blog/app/views/categories/index.html.erb
<h1 class="text-center">Categories</h1>

<table> 
    <thead>
    <tr>
        <th><%=sort_link(@q, :name)%></th>
        <th>Number of articles</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th>See more </th>
        <th>Articles </th>

    </tr>
    </thead>
    <tbody>
    <% @categories.each do |category| %>
    <tr>
        <td><%= category.name %></td>
        <td><%= category.articles.count %></td> 
        <td><%= l category.created_at %></td>
        <td><%= category.updated_at.strftime("%d/%m/%Y") %></td>
        <td><%= link_to category.name, category_path(category) %></td>
        <td><%= category.articles.map(&:title).join(", ") %></td>
    </tr>
    <% end %>
    </tbody>
</table>
<p></p>
<%== pagy_nav(@pagy) %>

alpha-blog/app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

alpha-blog/app/views/categories/show.html.erb
<h1>Showing category</h1>

<p><strong>Name : </strong>
    <%= @category.name %>

<p> Modifier nom catégorie : <%= link_to 'Edit', edit_category_path(@category) %></p>