alpha-blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'my_registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles # , only: [:show, :index, :new, :create, :edit, :update] #Creates the route needed
  resources :users, only: %i[index show]
  resources :categories, except: [:destroy]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :users, only: %i[index show]
  get 'upload_pic', to: 'users#upload_pic_get'
  post 'upload_pic_post', to: 'users#upload_pic_post'

  # Defines the root path route ("/")
  # root "posts#index"
end

#  get "/articles", to: "articles#index"  #The route above declares that GET /articles requests are mapped to the index
#   action of ArticlesController.

# resources :articles, only: [:show]

alpha-blog/app/models/user.rb
class User < ApplicationRecord
  extend Enumerize
  include ImageUploader::Attachment(:image) # adds an `image` virtual attribute
  def self.ransackable_attributes(_auth_object = nil)
    %w[
      id username email created_at updated_at
      encrypted_password reset_password_token
      reset_password_sent_at remember_created_at
      role profile_data image_data
    ]
  end

  def self.ransackable_associations(_auth_object = nil)
    ['articles']
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username, uniqueness: { case_sensitive: false },
                       presence: true, length: { minimum: 3, maximum: 25 }

  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'invalid email format' }
  enumerize :role, in: { restricted: 0, user: 1, admin: 2 }, default: :user, predicates: true
end

alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all

    @q = User.ransack(params[:q])
    result = @q.result(distinct: true)
    @users = result
  end

  def upload_pic_get
    @user = current_user
  end

  def upload_pic_post
    @user = current_user

    unless params[:photo] && params[:photo][:image]
      flash[:alert] = 'No image provided'
      redirect_to upload_pic_get_path
      return
    end

    @user.photo.attach(params[:photo][:image])

    if @user.save
      flash[:notice] = 'Profile picture was successfully uploaded'
      redirect_to user_path(@user)
    else
      flash[:alert] = 'Profile picture was not uploaded'
      render 'upload_pic_get', status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def user_image_params
    return unless params[:user] && params[:user][:image_data]

    @user.image = params[:user][:image_data] # Assign the uploaded file
  end
end

alpha-blog/app/views/users/index.html.erb
<h1> Users listing page </h1>
<table>
  <thead>
    <tr>
      <th><%=sort_link(@q, :username)%></th>
      <th>email</th>    
      <th>Nombre d'articles'</th>
        <th>Created at</th>
        <th>Role</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to "#{user.username}", user_path(user)%></td>
      <td><%= user.email%></td>
      <td><%= user.articles.count%></td>
      <td><%= user.created_at.strftime("%d %B %Y")%></td>
      <td><%= user.role%></td>

    </tr>
    <% end %>
  </tbody>
</table>
<p></p>
<%= link_to 'Créer un article', new_article_path%>

alpha-blog/app/views/users/show.html.erb
    <div class="card" style="width: 18rem;">
        <% if !@user.image_data%>
        <%= image_tag 'nopic.png', class: 'card-img-top', alt: 'No rofile pic' %>
        <% else %>
        <%= image_tag @user.image_url , class: 'card-img-top', alt: 'Profile pic' %>

        <% end%>
        <div class="card-body">
            <h5 class="card-title"> Username : <%= @user.username %></h5>
            <p class="card-text">
                Email : <%= @user.email %>

            </p>
            <% if @user == current_user%>
            <%= link_to 'Upload picture', upload_pic_path, class:'btn btn-primary'%>
            <% end%>
        </div>
    </div>

alpha-blog/app/views/users/upload_pic_get.html.erb
<% if @user%>
<%= form_for @user, url: upload_pic_post_path, method: :post, html: { multipart: true } do |f| %>
  <%= f.file_field :image_data %>
  <%= f.submit "Upload Picture" %>
<% end %>
<% end%>